apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-webapi
  namespace: argocd
  labels:
    app: webapi
    component: backend
    environment: dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/chanon-dev/poc-deploy-k8s.git
    targetRevision: main
    path: environments/dev
    directory:
      include: |
        webapi-deployment.yaml
        webapi-service.yaml
        configmap.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
