# ServiceAccount for External Secrets Operator in Jenkins namespace
# This SA will authenticate with Vault to fetch secrets

apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: jenkins
  labels:
    app: external-secrets
    component: vault-integration
