# ExternalSecret - syncs Harbor registry credentials from Vault to Kubernetes Secret
# The secret will be automatically created and kept in sync with Vault

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-secret
  namespace: jenkins
  labels:
    app: jenkins
    component: registry-credentials
spec:
  # Refresh interval - how often to sync from Vault
  refreshInterval: 1h

  # Reference to SecretStore
  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  # Target Kubernetes Secret
  target:
    name: harbor-registry-secret
    creationPolicy: Owner

    # Template to create docker-registry secret format
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        # Docker config.json format
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .registry }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }

  # Data to fetch from Vault
  data:
  - secretKey: registry
    remoteRef:
      key: ci/harbor
      property: registry

  - secretKey: username
    remoteRef:
      key: ci/harbor
      property: username

  - secretKey: password
    remoteRef:
      key: ci/harbor
      property: password
